### Quick review of tensors

In [1]:
import torch
import numpy as np

In [2]:
# Creating tensor from array
array = [[1, 2], [3 ,4]]
tensor = torch.tensor(array)

tensor

tensor([[1, 2],
        [3, 4]])

In [4]:
# Creating from np array
array_np = np.array([[1, 2], [3, 5]])
tensor = torch.from_numpy(array_np)

tensor

tensor([[1, 2],
        [3, 5]])

In [5]:
# Copying another tensor dimensions
ones = torch.ones_like(tensor, dtype = torch.float32)
ones

tensor([[1., 1.],
        [1., 1.]])

In [8]:
# Random array

# rand -> uniform distribution [0, 1)
rand = torch.rand(size=(2,3))

# randn -> normal distribution (mean 0, std 1)
randn = torch.randn_like(rand)

print(f"rand:\n{rand}")
print(f"randn:\n{randn}")

rand:
tensor([[0.2304, 0.8376, 0.1016],
        [0.6845, 0.7533, 0.4322]])
randn:
tensor([[-0.7721,  0.1152, -0.9705],
        [-0.0188,  0.0785, -1.0066]])


In [9]:
# attributes
print(f"shape: {randn.shape}")
print(f"dtype: {randn.dtype}")
print(f"device: {randn.device}")

shape: torch.Size([2, 3])
dtype: torch.float32
device: cpu


In [11]:
# modifying entire column
rand[:,1] = 0

# modifying entire row
randn[1,:] = -1

print(f"rand:\n{rand}")
print(f"randn:\n{randn}")

rand:
tensor([[0.2304, 0.0000, 0.1016],
        [0.6845, 0.0000, 0.4322]])
randn:
tensor([[-0.7721,  0.1152, -0.9705],
        [-1.0000, -1.0000, -1.0000]])


In [12]:
# concatenate
cat_row = torch.cat([rand, randn], dim = 0)
cat_col = torch.cat([rand, randn], dim = 1)

print(f"cat row:\n{cat_row}")
print(f"cat col:\n{cat_col}")

cat row:
tensor([[ 0.2304,  0.0000,  0.1016],
        [ 0.6845,  0.0000,  0.4322],
        [-0.7721,  0.1152, -0.9705],
        [-1.0000, -1.0000, -1.0000]])
cat col:
tensor([[ 0.2304,  0.0000,  0.1016, -0.7721,  0.1152, -0.9705],
        [ 0.6845,  0.0000,  0.4322, -1.0000, -1.0000, -1.0000]])
