In [1]:
import torch
import numpy as np

## Creating tensors

In [2]:
# Create tensors from list

data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
# Creating tensors from a numpy array

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"np_array:\n{np_array}")
print(f"tensor:\n{x_np}")

np_array:
[[1 2]
 [3 4]]
tensor:
tensor([[1, 2],
        [3, 4]])


In [4]:
# Creating from another tensor 

## keeping the properties (shape, datatype)
x_ones = torch.ones_like(x_data)

## Overriding the data type
x_rand = torch.rand_like(x_data, dtype = torch.float)

print(f"Keeping properties:\n{x_ones}")
print(f"Overriding properties:\n{x_rand}")

Keeping properties:
tensor([[1, 1],
        [1, 1]])
Overriding properties:
tensor([[0.6855, 0.2309],
        [0.1580, 0.8517]])


In [5]:
# Creating tensors with constant or random values

shape = (2,3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape, dtype=torch.int)
zeros_tensor = torch.zeros(shape)

print(f"Random:\n{rand_tensor}")
print(f"Ones:\n{ones_tensor}")
print(f"Zeros:\n{zeros_tensor}")

Random:
tensor([[0.4047, 0.9926, 0.4011],
        [0.8921, 0.0901, 0.0730]])
Ones:
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# Tensors attributes
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations

In [7]:
# Moving tensors to GPU if available

if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [8]:
# index and slicing

tensor = torch.rand(4,4)

print(f"Tensor:\n{tensor}")
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[...,0]}")
print(f"Last column: {tensor[:, -1]}")
print(f"Element 2x2 {tensor[1][1]}")

tensor[:,1] = 0

Tensor:
tensor([[0.5577, 0.3993, 0.5473, 0.8559],
        [0.9922, 0.4628, 0.1820, 0.6571],
        [0.8470, 0.7660, 0.9721, 0.5732],
        [0.5422, 0.3252, 0.1055, 0.3579]])
First row: tensor([0.5577, 0.3993, 0.5473, 0.8559])
First column: tensor([0.5577, 0.9922, 0.8470, 0.5422])
Last column: tensor([0.8559, 0.6571, 0.5732, 0.3579])
Element 2x2 0.46282583475112915


In [9]:
# Concatenating tensors
t1 = torch.ones(4,4)
t0 = torch.zeros(4,4)

column_concat = torch.cat([t1,t0], axis = 1)
row_concat = torch.cat([t1,t0], axis = 0)

print(f"Columns cancat:\n{column_concat}")
print(f"Rows cancat:\n{row_concat}")

Columns cancat:
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
Rows cancat:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [10]:
tensor = torch.ones(4, 4)
tensor[:,1]=0

t1 = torch.tensor([[1, 2],[3,4]])
t2 = torch.tensor([[5, 6],[7,8]])

# Arithmetic operations
# matrix multiplication (3 ways)
y1 = t1 @ t2
y2 = t1.matmul(t2)

y3 = torch.ones_like(y1)
torch.matmul(t1, t2, out = y3)

print(y1)
print(y2)
print(y3)

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [11]:
# Element-wise product (3 ways)
z1 = t1 * t2
z2 = t1.mul(t2)

z3 = torch.ones_like(z1)
torch.mul(t1, t2, out = z3)

print(z1)
print(z2)
print(z3)

tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])


In [12]:
# converting 1 element tensor to numerical using 'item()' 
aggregated = z3.sum()
aggregated_item = aggregated.item()

print(aggregated_item, type(aggregated_item))

70 <class 'int'>


In [13]:
# IN-PLACE operations -> operations that store the result of an expression into the operand. Denoted by _ suffix (add_())

tensor = torch.tensor([[1, 1, 0], [0, 1, 1], [1, 0, 1]])
print(f"Tensor:\n{tensor}")
tensor.add_(5)
print(f"Tensor:\n{tensor}")

Tensor:
tensor([[1, 1, 0],
        [0, 1, 1],
        [1, 0, 1]])
Tensor:
tensor([[6, 6, 5],
        [5, 6, 6],
        [6, 5, 6]])


## Bridge to numpy

In [14]:
# If a tensor is converted to numpy, all the modifications on the tensor reflect on the array

t = torch.ones(5)
n = t.numpy()

print(f"t:\n{t}")
print(f"n:\n{n}")

t.add_(2)

print(f"t:\n{t}")
print(f"n:\n{n}")

t:
tensor([1., 1., 1., 1., 1.])
n:
[1. 1. 1. 1. 1.]
t:
tensor([3., 3., 3., 3., 3.])
n:
[3. 3. 3. 3. 3.]


In [15]:
# When converting a numpy array to a tensor they also keep the same reference
n = np.ones(5)
t = torch.from_numpy(n)

print(f"n:\n{n}")
print(f"t:\n{t}")

np.add(n, 1, out = n)
print(f"n:\n{n}")
print(f"t:\n{t}")

n:
[1. 1. 1. 1. 1.]
t:
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n:
[2. 2. 2. 2. 2.]
t:
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
